# Generated by Django 6.0.4 on 2026-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('SEO & Search', 'SEO & Search'), ('Social Media Marketing', 'Social Media Marketing'), ('Paid Advertising (PPC)', 'Paid Advertising (PPC)'), ('Content Marketing', 'Content Marketing'), ('Branding & Identity', 'Branding & Identity'), ('Website & Conversion Optimizations', 'Website & Conversion Optimizations'), ('Email Marketing', 'Email Marketing'), ('Analytics & Reporting', 'Analytics & Reporting'), ('Local Marketing', 'Local Marketing'), ('Digital Marketing for Industries', 'Digital Marketing for Industries')], max_length=50),
        ),
    ]
